### ISSUE TITLE
tabs instead of spaces?

### ISSUE THREAD

**Issue by pescobar** [pearofducks/ansible-vim#26]
Hi 

I am using this in my default vimrc to do tab = 2 spaces

```
" for yaml files (ansible playbooks) <tab> = 2 spaces
autocmd FileType yaml set tabstop=2|set shiftwidth=2
```

After installing this plugin when I use tab in a playbook I get a tab (`^I` ) instead of two spaces (checked with `set list`) and then I get syntax errors when trying to run the playbook.

What am I doing wrong? Any suggestion to fix this? I have installed the plugin using pathogen

**Comment by pearofducks** [comment]
That setting won't affect any files this plugin deals with. You're setting *yaml* files to have this preference, this plugin doesn't work with *yaml* files, it works with *ansible* files.

To see what kind of file Vim thinks you're editing, you can do: `echo &ft`

Otherwise, with that setting on either yaml or ansible filetypes I cannot reproduce the behavior!

**Comment by pescobar** [comment]
I found a fix by upgrading pathogen to the latest version and changing my `~/.vimrc` from this:

```
call pathogen#infect()
filetype plugin on
```

To this:

```
execute pathogen#infect()
filetype plugin indent on
```

Now it's working fine and the tab key is adding two spaces instead of a tab
