### ISSUE TITLE
Feature request:  set wildignore+=*.retry

### ISSUE THREAD

**Issue by BrianAker** [pearofducks/ansible-vim#30]
If you included the following:
set wildignore+=*.retry

Adding it would cause the retry files to be ignored during tab completion. 

Adding ignore is not an uncommon practice for vim modules. Vundle, c.vim, and others make use of this feature today.

**Comment by pearofducks** [comment]
While others might set wildignore, I think this is generally done when there are a lot of files to be ignored - e.g. `*.o` files in _c.vim_. I'd really like this plugin to not prescribe too many settings to the user, and to that end I've kept even the syntax colors configurable.

Since this is easily able to be set in the user's vimrc, I'd prefer to mention it in the README, rather than build it in.
